
-------------------- Simple.dfy --------------------
// Simple.dfy

class MyClass<T, U> {
  var x: int;

  method M(s: bool, lotsaObjects: set<object>)
      returns (t: object, u: set<int>, v: seq<MyClass<bool,U>>)
    requires s;
    modifies this, lotsaObjects;
    ensures t == t;
    ensures old(null) != this;
  {
    x := 12;
    while x < 100
      invariant x <= 100;
    {
      x := x + 17;
      if x % 20 == 3 {
        x := this.x + 1;
      } else {
        this.x := x + 0;
      }
      t, u, v := M(true, lotsaObjects);
      var to: MyClass<T,U>;
      to, u, v := this.M(true, lotsaObjects);
      to, u, v := to.M(true, lotsaObjects);
      assert v[x] != null ==> null !in v[2 .. x][1..][5 := v[this.x]][..10];
    }
  }

  function F(x: int, y: int, h: WildData, k: WildData): WildData
  {
    if x < 0 then
      h
    else if x == 0 then
      if if h == k then true else false then
        h
      else if y == 0 then
        k
      else
        h
    else
      k
  }
}

datatype List<T> = Nil | Cons(T, List<T>)

datatype WildData = Something | JustAboutAnything(bool, myName: set<int>, int, WildData) | More(List<int>)

class C {
  var w: WildData;
  var list: List<bool>;
}

lemma M(x: int)
  ensures x < 8;
{
}

comethod M'(x': int)
  ensures true;
{
}

Dafny program verifier finished with 0 verified, 0 errors

-------------------- TypeTests.dfy --------------------
TypeTests.dfy(4,13): Error: incorrect type of function argument 0 (expected C, got D)
TypeTests.dfy(4,13): Error: incorrect type of function argument 1 (expected D, got C)
TypeTests.dfy(5,13): Error: incorrect type of function argument 0 (expected C, got int)
TypeTests.dfy(5,13): Error: incorrect type of function argument 1 (expected D, got int)
TypeTests.dfy(11,15): Error: incorrect type of method in-parameter 0 (expected int, got bool)
TypeTests.dfy(12,11): Error: incorrect type of method out-parameter 0 (expected int, got C)
TypeTests.dfy(12,11): Error: incorrect type of method out-parameter 1 (expected C, got int)
TypeTests.dfy(44,9): Error: Assignment to array element is not allowed in this context (because this is a ghost method or because the statement is guarded by a specification-only expression)
TypeTests.dfy(53,6): Error: Duplicate local-variable name: z
TypeTests.dfy(55,6): Error: Duplicate local-variable name: x
TypeTests.dfy(58,8): Error: Duplicate local-variable name: x
TypeTests.dfy(61,6): Error: Duplicate local-variable name: y
TypeTests.dfy(68,17): Error: member F in type C does not refer to a method
TypeTests.dfy(69,17): Error: a method called as an initialization method must not have any result arguments
TypeTests.dfy(78,3): Error: cannot assign to a range of array elements (try the 'forall' statement)
TypeTests.dfy(79,3): Error: cannot assign to a range of array elements (try the 'forall' statement)
TypeTests.dfy(80,3): Error: cannot assign to a range of array elements (try the 'forall' statement)
TypeTests.dfy(82,3): Error: cannot assign to a range of array elements (try the 'forall' statement)
TypeTests.dfy(83,3): Error: cannot assign to a range of array elements (try the 'forall' statement)
TypeTests.dfy(84,3): Error: cannot assign to a range of array elements (try the 'forall' statement)
TypeTests.dfy(90,6): Error: sorry, cannot instantiate collection type with a subrange type
TypeTests.dfy(91,9): Error: sorry, cannot instantiate type parameter with a subrange type
TypeTests.dfy(92,8): Error: sorry, cannot instantiate 'array' type with a subrange type
TypeTests.dfy(93,8): Error: sorry, cannot instantiate 'array' type with a subrange type
TypeTests.dfy(105,15): Error: ghost variables are allowed only in specification contexts
TypeTests.dfy(115,4): Error: cannot assign to non-ghost variable in a ghost context
TypeTests.dfy(116,7): Error: cannot assign to non-ghost variable in a ghost context
TypeTests.dfy(18,9): Error: because of cyclic dependencies among constructor argument types, no instances of datatype 'NeverendingList' can be constructed
28 resolution/type errors detected in TypeTests.dfy

-------------------- NatTypes.dfy --------------------
NatTypes.dfy(7,5): Error: value assigned to a nat must be non-negative
Execution trace:
    (0,0): anon0
NatTypes.dfy(31,10): Error: value assigned to a nat must be non-negative
Execution trace:
    (0,0): anon0
    NatTypes.dfy(19,3): anon10_LoopHead
    (0,0): anon10_LoopBody
    NatTypes.dfy(19,3): anon11_Else
    (0,0): anon12_Then
NatTypes.dfy(38,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then
NatTypes.dfy(40,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then
NatTypes.dfy(57,16): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
NatTypes.dfy(71,16): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Then
NatTypes.dfy(89,19): Error: value assigned to a nat must be non-negative
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
NatTypes.dfy(104,45): Error: value assigned to a nat must be non-negative
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
    (0,0): anon7_Else
    (0,0): anon8_Then
NatTypes.dfy(127,21): Error: value assigned to a nat must be non-negative
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then

Dafny program verifier finished with 15 verified, 9 errors

-------------------- Definedness.dfy --------------------
Definedness.dfy(8,7): Error: possible division by zero
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
Definedness.dfy(15,16): Error: possible division by zero
Execution trace:
    (0,0): anon0
Definedness.dfy(24,16): Error: target object may be null
Execution trace:
    (0,0): anon0
Definedness.dfy(25,21): Error: target object may be null
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
Definedness.dfy(26,17): Error: possible division by zero
Execution trace:
    (0,0): anon0
Definedness.dfy(33,16): Error: target object may be null
Execution trace:
    (0,0): anon0
Definedness.dfy(42,16): Error: target object may be null
Execution trace:
    (0,0): anon0
Definedness.dfy(50,18): Error: target object may be null
Execution trace:
    (0,0): anon0
Definedness.dfy(51,3): Error BP5003: A postcondition might not hold on this return path.
Definedness.dfy(50,22): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
Definedness.dfy(57,18): Error: target object may be null
Execution trace:
    (0,0): anon0
Definedness.dfy(58,3): Error BP5003: A postcondition might not hold on this return path.
Definedness.dfy(57,22): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
Definedness.dfy(65,3): Error BP5003: A postcondition might not hold on this return path.
Definedness.dfy(64,22): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
Definedness.dfy(85,7): Error: target object may be null
Execution trace:
    (0,0): anon0
Definedness.dfy(86,5): Error: possible violation of function precondition
Execution trace:
    (0,0): anon0
Definedness.dfy(86,10): Error: assignment may update an object not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
Definedness.dfy(86,10): Error: target object may be null
Execution trace:
    (0,0): anon0
Definedness.dfy(87,10): Error: possible violation of function precondition
Execution trace:
    (0,0): anon0
Definedness.dfy(92,14): Error: possible division by zero
Execution trace:
    (0,0): anon0
Definedness.dfy(92,23): Error: possible division by zero
Execution trace:
    (0,0): anon0
Definedness.dfy(93,15): Error: possible division by zero
Execution trace:
    (0,0): anon0
Definedness.dfy(98,12): Error: possible division by zero
Execution trace:
    (0,0): anon0
Definedness.dfy(105,15): Error: possible division by zero
Execution trace:
    Definedness.dfy(105,5): anon7_LoopHead
    (0,0): anon7_LoopBody
    Definedness.dfy(105,5): anon8_Else
Definedness.dfy(114,23): Error: possible violation of function precondition
Execution trace:
    (0,0): anon0
    Definedness.dfy(113,5): anon12_LoopHead
    (0,0): anon12_LoopBody
    (0,0): anon13_Then
Definedness.dfy(120,17): Error: possible violation of function precondition
Execution trace:
    (0,0): anon0
    Definedness.dfy(113,5): anon12_LoopHead
    (0,0): anon12_LoopBody
    Definedness.dfy(113,5): anon13_Else
    (0,0): anon14_Then
    Definedness.dfy(119,5): anon15_LoopHead
    (0,0): anon15_LoopBody
    (0,0): anon16_Then
Definedness.dfy(130,17): Error: possible violation of function precondition
Execution trace:
    (0,0): anon0
    Definedness.dfy(129,5): anon6_LoopHead
    (0,0): anon6_LoopBody
    (0,0): anon7_Then
Definedness.dfy(130,22): Error BP5004: This loop invariant might not hold on entry.
Execution trace:
    (0,0): anon0
Definedness.dfy(131,17): Error: possible violation of function precondition
Execution trace:
    (0,0): anon0
    Definedness.dfy(129,5): anon6_LoopHead
    (0,0): anon6_LoopBody
    (0,0): anon7_Then
Definedness.dfy(140,15): Error: possible division by zero
Execution trace:
    (0,0): anon0
    Definedness.dfy(140,5): anon8_LoopHead
    (0,0): anon8_LoopBody
    Definedness.dfy(140,5): anon9_Else
Definedness.dfy(159,15): Error: possible division by zero
Execution trace:
    (0,0): anon0
    Definedness.dfy(153,5): anon16_LoopHead
    (0,0): anon16_LoopBody
    Definedness.dfy(153,5): anon17_Else
    (0,0): anon18_Then
    (0,0): anon5
    (0,0): anon19_Then
    Definedness.dfy(159,5): anon20_LoopHead
    (0,0): anon20_LoopBody
    Definedness.dfy(159,5): anon21_Else
Definedness.dfy(172,28): Error BP5004: This loop invariant might not hold on entry.
Execution trace:
    (0,0): anon0
Definedness.dfy(178,17): Error: possible violation of function precondition
Execution trace:
    (0,0): anon0
    Definedness.dfy(170,5): anon18_LoopHead
    (0,0): anon18_LoopBody
    Definedness.dfy(170,5): anon19_Else
    (0,0): anon20_Then
    Definedness.dfy(177,5): anon21_LoopHead
    (0,0): anon21_LoopBody
    (0,0): anon22_Then
    (0,0): anon23_Then
    (0,0): anon11
Definedness.dfy(193,19): Error: possible division by zero
Execution trace:
    (0,0): anon0
    Definedness.dfy(191,5): anon6_LoopHead
    (0,0): anon6_LoopBody
    (0,0): anon7_Then
Definedness.dfy(193,23): Error BP5004: This loop invariant might not hold on entry.
Execution trace:
    (0,0): anon0
Definedness.dfy(193,28): Error: possible division by zero
Execution trace:
    (0,0): anon0
    Definedness.dfy(191,5): anon6_LoopHead
    (0,0): anon6_LoopBody
    (0,0): anon7_Then
Definedness.dfy(212,10): Error BP5003: A postcondition might not hold on this return path.
Definedness.dfy(214,46): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
Definedness.dfy(221,22): Error: target object may be null
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon2
    (0,0): anon6_Then
Definedness.dfy(234,10): Error BP5003: A postcondition might not hold on this return path.
Definedness.dfy(237,24): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon7_Then
    (0,0): anon2
    (0,0): anon8_Else

Dafny program verifier finished with 21 verified, 37 errors

-------------------- FunctionSpecifications.dfy --------------------
FunctionSpecifications.dfy(32,25): Error BP5003: A postcondition might not hold on this return path.
FunctionSpecifications.dfy(28,13): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon8_Else
    (0,0): anon9_Else
    (0,0): anon10_Then
    (0,0): anon11_Else
FunctionSpecifications.dfy(42,3): Error BP5003: A postcondition might not hold on this return path.
FunctionSpecifications.dfy(37,24): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon11_Else
    (0,0): anon14_Else
    (0,0): anon15_Then
FunctionSpecifications.dfy(50,11): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon8_Then
    (0,0): anon3
FunctionSpecifications.dfy(56,10): Error BP5003: A postcondition might not hold on this return path.
FunctionSpecifications.dfy(57,22): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
FunctionSpecifications.dfy(105,23): Error: assertion violation
Execution trace:
    (0,0): anon0
FunctionSpecifications.dfy(108,23): Error: assertion violation
Execution trace:
    (0,0): anon0
FunctionSpecifications.dfy(123,27): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
FunctionSpecifications.dfy(127,27): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
FunctionSpecifications.dfy(150,15): Error: assertion violation
Execution trace:
    (0,0): anon0
FunctionSpecifications.dfy(162,3): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
FunctionSpecifications.dfy(169,15): Error: assertion violation
Execution trace:
    (0,0): anon0
FunctionSpecifications.dfy(178,3): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
FunctionSpecifications.dfy(132,20): Error BP5003: A postcondition might not hold on this return path.
FunctionSpecifications.dfy(134,29): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon2
    (0,0): anon6_Else
FunctionSpecifications.dfy(143,3): Error: failure to decrease termination measure
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
FunctionSpecifications.dfy(157,3): Error: failure to decrease termination measure
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
FunctionSpecifications.dfy(185,3): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
FunctionSpecifications.dfy(182,20): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 19 verified, 17 errors

-------------------- ResolutionErrors.dfy --------------------
ResolutionErrors.dfy(497,7): Error: RHS (of type List<A>) not assignable to LHS (of type List<B>)
ResolutionErrors.dfy(502,7): Error: RHS (of type List<A>) not assignable to LHS (of type List<B>)
ResolutionErrors.dfy(516,23): Error: type of case bodies do not agree (found Tree<_T1,_T0>, previous types Tree<_T0,_T1>)
ResolutionErrors.dfy(528,24): Error: Wrong number of type arguments (0 instead of 2) passed to class/datatype: Tree
ResolutionErrors.dfy(563,18): Error: type of bound variable 'z' could not determined; please specify the type explicitly
ResolutionErrors.dfy(576,13): Error: 'new' is not allowed in ghost contexts
ResolutionErrors.dfy(577,9): Error: 'new' is not allowed in ghost contexts
ResolutionErrors.dfy(584,14): Error: new allocation not supported in forall statements
ResolutionErrors.dfy(589,11): Error: the body of the enclosing forall statement is not allowed to update heap locations
ResolutionErrors.dfy(589,14): Error: new allocation not allowed in ghost context
ResolutionErrors.dfy(599,23): Error: 'new' is not allowed in ghost contexts
ResolutionErrors.dfy(606,15): Error: 'new' is not allowed in ghost contexts
ResolutionErrors.dfy(606,15): Error: only ghost methods can be called from this context
ResolutionErrors.dfy(606,10): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(615,17): Error: 'new' is not allowed in ghost contexts
ResolutionErrors.dfy(617,20): Error: only ghost methods can be called from this context
ResolutionErrors.dfy(619,8): Error: calls to methods with side-effects are not allowed inside a hint
ResolutionErrors.dfy(637,21): Error: the type of this expression is underspecified, but it cannot be an arbitrary type.
ResolutionErrors.dfy(637,21): Error: the type of this expression is underspecified, but it cannot be an arbitrary type.
ResolutionErrors.dfy(674,8): Error: calls to methods with side-effects are not allowed inside a hint
ResolutionErrors.dfy(684,8): Error: only ghost methods can be called from this context
ResolutionErrors.dfy(687,20): Error: 'decreases *' is not allowed on ghost loops
ResolutionErrors.dfy(698,16): Error: Assignment to non-ghost field is not allowed in this context (because this is a ghost method or because the statement is guarded by a specification-only expression)
ResolutionErrors.dfy(698,16): Error: a hint is not allowed to update heap locations
ResolutionErrors.dfy(699,21): Error: a hint is not allowed to update heap locations
ResolutionErrors.dfy(700,8): Error: calls to methods with side-effects are not allowed inside a hint
ResolutionErrors.dfy(703,19): Error: a while statement used inside a hint is not allowed to have a modifies clause
ResolutionErrors.dfy(722,8): Error: only ghost methods can be called from this context
ResolutionErrors.dfy(725,20): Error: 'decreases *' is not allowed on ghost loops
ResolutionErrors.dfy(730,16): Error: Assignment to non-ghost field is not allowed in this context (because this is a ghost method or because the statement is guarded by a specification-only expression)
ResolutionErrors.dfy(730,16): Error: a hint is not allowed to update heap locations
ResolutionErrors.dfy(731,21): Error: a hint is not allowed to update heap locations
ResolutionErrors.dfy(732,8): Error: calls to methods with side-effects are not allowed inside a hint
ResolutionErrors.dfy(735,19): Error: a while statement used inside a hint is not allowed to have a modifies clause
ResolutionErrors.dfy(760,4): Error: calls to methods with side-effects are not allowed inside a statement expression
ResolutionErrors.dfy(761,4): Error: only ghost methods can be called from this context
ResolutionErrors.dfy(762,4): Error: wrong number of method result arguments (got 0, expected 1)
ResolutionErrors.dfy(773,23): Error: function calls are allowed only in specification contexts (consider declaring the function a 'function method')
ResolutionErrors.dfy(783,4): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(794,36): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(803,17): Error: function calls are allowed only in specification contexts (consider declaring the function a 'function method')
ResolutionErrors.dfy(427,2): Error: More than one default constructor
ResolutionErrors.dfy(48,13): Error: 'this' is not allowed in a 'static' context
ResolutionErrors.dfy(109,9): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(110,9): Error: function calls are allowed only in specification contexts (consider declaring the function a 'function method')
ResolutionErrors.dfy(114,11): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(115,9): Error: actual out-parameter 0 is required to be a ghost variable
ResolutionErrors.dfy(122,15): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(126,23): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(133,4): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(137,21): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(138,35): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(147,9): Error: only ghost methods can be called from this context
ResolutionErrors.dfy(153,16): Error: 'decreases *' is not allowed on ghost loops
ResolutionErrors.dfy(194,27): Error: ghost-context break statement is not allowed to break out of non-ghost structure
ResolutionErrors.dfy(217,12): Error: ghost-context break statement is not allowed to break out of non-ghost loop
ResolutionErrors.dfy(229,12): Error: trying to break out of more loop levels than there are enclosing loops
ResolutionErrors.dfy(233,12): Error: ghost-context break statement is not allowed to break out of non-ghost loop
ResolutionErrors.dfy(238,8): Error: return statement is not allowed in this context (because it is guarded by a specification-only expression)
ResolutionErrors.dfy(433,14): Error: when allocating an object of type 'YHWH', one of its constructor methods must be called
ResolutionErrors.dfy(438,6): Error: when allocating an object of type 'Lucifer', one of its constructor methods must be called
ResolutionErrors.dfy(439,6): Error: when allocating an object of type 'Lucifer', one of its constructor methods must be called
ResolutionErrors.dfy(441,9): Error: class Lamb does not have a default constructor
ResolutionErrors.dfy(10,16): Error: 'decreases *' is not allowed on ghost loops
ResolutionErrors.dfy(22,11): Error: array selection requires an array2 (got array3<T>)
ResolutionErrors.dfy(23,12): Error: sequence/array/multiset/map selection requires a sequence, array, multiset, or map (got array3<T>)
ResolutionErrors.dfy(24,11): Error: array selection requires an array4 (got array<T>)
ResolutionErrors.dfy(54,14): Error: a field must be selected via an object, not just a class name
ResolutionErrors.dfy(55,7): Error: unresolved identifier: F
ResolutionErrors.dfy(56,14): Error: an instance function must be selected via an object, not just a class name
ResolutionErrors.dfy(56,7): Error: call to instance function requires an instance
ResolutionErrors.dfy(57,7): Error: unresolved identifier: G
ResolutionErrors.dfy(59,7): Error: unresolved identifier: M
ResolutionErrors.dfy(60,7): Error: call to instance method requires an instance
ResolutionErrors.dfy(61,7): Error: unresolved identifier: N
ResolutionErrors.dfy(64,8): Error: non-function expression is called with parameters
ResolutionErrors.dfy(65,14): Error: member z does not exist in class Global
ResolutionErrors.dfy(84,12): Error: the name 'Benny' denotes a datatype constructor, but does not do so uniquely; add an explicit qualification (for example, 'Abc.Benny')
ResolutionErrors.dfy(89,12): Error: the name 'David' denotes a datatype constructor, but does not do so uniquely; add an explicit qualification (for example, 'Abc.David')
ResolutionErrors.dfy(90,12): Error: the name 'David' denotes a datatype constructor, but does not do so uniquely; add an explicit qualification (for example, 'Abc.David')
ResolutionErrors.dfy(92,12): Error: the name 'David' denotes a datatype constructor, but does not do so uniquely; add an explicit qualification (for example, 'Abc.David')
ResolutionErrors.dfy(94,12): Error: wrong number of arguments to datatype constructor Abc (found 2, expected 1)
ResolutionErrors.dfy(256,4): Error: label shadows an enclosing label
ResolutionErrors.dfy(261,2): Error: duplicate label
ResolutionErrors.dfy(287,4): Error: when allocating an object of type 'ClassWithConstructor', one of its constructor methods must be called
ResolutionErrors.dfy(288,4): Error: when allocating an object of type 'ClassWithConstructor', one of its constructor methods must be called
ResolutionErrors.dfy(290,4): Error: a constructor is only allowed to be called when an object is being allocated
ResolutionErrors.dfy(304,16): Error: arguments must have the same type (got int and DTD_List)
ResolutionErrors.dfy(305,16): Error: arguments must have the same type (got DTD_List and int)
ResolutionErrors.dfy(306,25): Error: arguments must have the same type (got bool and int)
ResolutionErrors.dfy(309,18): Error: ghost fields are allowed only in specification contexts
ResolutionErrors.dfy(318,15): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(343,2): Error: incorrect type of method in-parameter 1 (expected GenericClass<int>, got GenericClass<bool>)
ResolutionErrors.dfy(355,18): Error: incorrect type of datatype constructor argument (found GList<_T0>, expected GList<int>)
ResolutionErrors.dfy(363,6): Error: arguments to + must be int or a collection type (instead got bool)
ResolutionErrors.dfy(368,6): Error: all lines in a calculation must have the same type (got int after bool)
ResolutionErrors.dfy(371,6): Error: first argument to ==> must be of type bool (instead got int)
ResolutionErrors.dfy(371,6): Error: second argument to ==> must be of type bool (instead got int)
ResolutionErrors.dfy(372,10): Error: first argument to ==> must be of type bool (instead got int)
ResolutionErrors.dfy(372,10): Error: second argument to ==> must be of type bool (instead got int)
ResolutionErrors.dfy(377,10): Error: first argument to ==> must be of type bool (instead got int)
ResolutionErrors.dfy(377,10): Error: second argument to ==> must be of type bool (instead got int)
ResolutionErrors.dfy(382,6): Error: print statement is not allowed in this context (because this is a ghost method or because the statement is guarded by a specification-only expression)
ResolutionErrors.dfy(404,6): Error: calls to methods with side-effects are not allowed inside a hint
ResolutionErrors.dfy(406,12): Error: a hint is not allowed to update heap locations
ResolutionErrors.dfy(408,8): Error: a hint is not allowed to update a variable declared outside the hint
ResolutionErrors.dfy(465,7): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(471,12): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(539,7): Error: let-such-that expressions are allowed only in ghost contexts
ResolutionErrors.dfy(541,7): Error: let-such-that expressions are allowed only in ghost contexts
ResolutionErrors.dfy(541,20): Error: ghost variables are allowed only in specification contexts
ResolutionErrors.dfy(543,7): Error: let-such-that expressions are allowed only in ghost contexts
ResolutionErrors.dfy(544,18): Error: unresolved identifier: w
ResolutionErrors.dfy(651,11): Error: lemmas are not allowed to have modifies clauses
114 resolution/type errors detected in ResolutionErrors.dfy

-------------------- ParseErrors.dfy --------------------
ParseErrors.dfy(4,19): error: a chain cannot have more than one != operator
ParseErrors.dfy(6,37): error: this operator chain cannot continue with a descending operator
ParseErrors.dfy(7,38): error: this operator chain cannot continue with an ascending operator
ParseErrors.dfy(12,24): error: this operator chain cannot continue with a descending operator
ParseErrors.dfy(15,18): error: this operator cannot be part of a chain
ParseErrors.dfy(16,19): error: this operator cannot be part of a chain
ParseErrors.dfy(17,18): error: this operator cannot be part of a chain
ParseErrors.dfy(18,18): error: chaining not allowed from the previous operator
ParseErrors.dfy(46,8): error: the main operator of a calculation must be transitive
ParseErrors.dfy(62,2): error: this operator cannot continue this calculation
ParseErrors.dfy(63,2): error: this operator cannot continue this calculation
ParseErrors.dfy(68,2): error: this operator cannot continue this calculation
ParseErrors.dfy(69,2): error: this operator cannot continue this calculation
ParseErrors.dfy(75,2): error: this operator cannot continue this calculation
14 parse errors detected in ParseErrors.dfy

-------------------- Array.dfy --------------------
Array.dfy(10,8): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon2
    (0,0): anon6_Then
Array.dfy(17,16): Error: target object may be null
Execution trace:
    (0,0): anon0
Array.dfy(24,6): Error: index out of range
Execution trace:
    (0,0): anon0
Array.dfy(48,20): Error: assertion violation
Execution trace:
    (0,0): anon0
Array.dfy(56,8): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon2
    (0,0): anon6_Then
Array.dfy(63,8): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon2
    (0,0): anon6_Then
Array.dfy(107,21): Error: upper bound below lower bound or above length of array
Execution trace:
    (0,0): anon0
    (0,0): anon14_Else
    (0,0): anon18_Then
    (0,0): anon19_Then
    (0,0): anon20_Then
    (0,0): anon11
Array.dfy(117,8): Error: insufficient reads clause to read the indicated range of array elements
Execution trace:
    (0,0): anon0
    (0,0): anon9_Else
    (0,0): anon10_Then
    (0,0): anon11_Then
    (0,0): anon12_Then
Array.dfy(119,8): Error: insufficient reads clause to read the indicated range of array elements
Execution trace:
    (0,0): anon0
    (0,0): anon9_Else
    (0,0): anon10_Then
    (0,0): anon11_Then
    (0,0): anon12_Else
Array.dfy(120,8): Error: insufficient reads clause to read the indicated range of array elements
Execution trace:
    (0,0): anon0
    (0,0): anon9_Else
    (0,0): anon10_Then
    (0,0): anon11_Then
    (0,0): anon12_Else
Array.dfy(121,8): Error: insufficient reads clause to read the indicated range of array elements
Execution trace:
    (0,0): anon0
    (0,0): anon9_Else
    (0,0): anon10_Then
    (0,0): anon11_Then
    (0,0): anon12_Else
Array.dfy(147,6): Error: insufficient reads clause to read array element
Execution trace:
    (0,0): anon0
    (0,0): anon7_Else
    (0,0): anon8_Then
    (0,0): anon9_Then
Array.dfy(155,6): Error: insufficient reads clause to read array element
Execution trace:
    (0,0): anon0
    (0,0): anon7_Else
    (0,0): anon8_Then
    (0,0): anon9_Then
Array.dfy(171,6): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
Array.dfy(178,6): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
Array.dfy(203,1): Error BP5003: A postcondition might not hold on this return path.
Array.dfy(202,11): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
Array.dfy(227,1): Error BP5003: A postcondition might not hold on this return path.
Array.dfy(226,11): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
Array.dfy(233,1): Error BP5003: A postcondition might not hold on this return path.
Array.dfy(232,11): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
Array.dfy(248,10): Error: value assigned to a nat must be non-negative
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon2
    (0,0): anon6_Then
Array.dfy(249,5): Error: value assigned to a nat must be non-negative
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon2
    (0,0): anon6_Then

Dafny program verifier finished with 34 verified, 20 errors

-------------------- MultiDimArray.dfy --------------------
MultiDimArray.dfy(53,21): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon11_Then
    (0,0): anon12_Then
MultiDimArray.dfy(80,25): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon6_Then

Dafny program verifier finished with 8 verified, 2 errors

-------------------- NonGhostQuantifiers.dfy --------------------
NonGhostQuantifiers.dfy(146,4): Error: a quantifier involved in a function definition is not allowed to depend on the set of allocated references; Dafny's heuristics can't figure out a bound for the values of 'c'
NonGhostQuantifiers.dfy(150,4): Error: a quantifier involved in a function definition is not allowed to depend on the set of allocated references; Dafny's heuristics can't figure out a bound for the values of 'c'
NonGhostQuantifiers.dfy(155,4): Error: a quantifier involved in a function definition is not allowed to depend on the set of allocated references; Dafny's heuristics can't figure out a bound for the values of 'c'
NonGhostQuantifiers.dfy(160,4): Error: a quantifier involved in a function definition is not allowed to depend on the set of allocated references; Dafny's heuristics can't figure out a bound for the values of 'c'
NonGhostQuantifiers.dfy(164,4): Error: a quantifier involved in a function definition is not allowed to depend on the set of allocated references; Dafny's heuristics can't figure out a bound for the values of 'c'
NonGhostQuantifiers.dfy(168,4): Error: a quantifier involved in a function definition is not allowed to depend on the set of allocated references; Dafny's heuristics can't figure out a bound for the values of 'c'
NonGhostQuantifiers.dfy(173,4): Error: a quantifier involved in a function definition is not allowed to depend on the set of allocated references; Dafny's heuristics can't figure out a bound for the values of 'c'
NonGhostQuantifiers.dfy(178,4): Error: a quantifier involved in a function definition is not allowed to depend on the set of allocated references; Dafny's heuristics can't figure out a bound for the values of 'c'
NonGhostQuantifiers.dfy(183,13): Error: quantifiers in non-ghost contexts must be compilable, but Dafny's heuristics can't figure out how to produce a bounded set of values for 'c'
NonGhostQuantifiers.dfy(13,5): Error: quantifiers in non-ghost contexts must be compilable, but Dafny's heuristics can't figure out how to produce a bounded set of values for 'n'
NonGhostQuantifiers.dfy(42,4): Error: quantifiers in non-ghost contexts must be compilable, but Dafny's heuristics can't figure out how to produce a bounded set of values for 'n'
NonGhostQuantifiers.dfy(46,4): Error: quantifiers in non-ghost contexts must be compilable, but Dafny's heuristics can't figure out how to produce a bounded set of values for 'd'
NonGhostQuantifiers.dfy(50,4): Error: quantifiers in non-ghost contexts must be compilable, but Dafny's heuristics can't figure out how to produce a bounded set of values for 'n'
NonGhostQuantifiers.dfy(74,5): Error: quantifiers in non-ghost contexts must be compilable, but Dafny's heuristics can't figure out how to produce a bounded set of values for 'i'
NonGhostQuantifiers.dfy(78,5): Error: quantifiers in non-ghost contexts must be compilable, but Dafny's heuristics can't figure out how to produce a bounded set of values for 'j'
NonGhostQuantifiers.dfy(88,5): Error: quantifiers in non-ghost contexts must be compilable, but Dafny's heuristics can't figure out how to produce a bounded set of values for 'j'
NonGhostQuantifiers.dfy(103,5): Error: quantifiers in non-ghost contexts must be compilable, but Dafny's heuristics can't figure out how to produce a bounded set of values for 'j'
NonGhostQuantifiers.dfy(111,10): Error: quantifiers in non-ghost contexts must be compilable, but Dafny's heuristics can't figure out how to produce a bounded set of values for 'y'
NonGhostQuantifiers.dfy(120,8): Error: quantifiers in non-ghost contexts must be compilable, but Dafny's heuristics can't figure out how to produce a bounded set of values for 'x'
NonGhostQuantifiers.dfy(137,8): Error: Assignment to non-ghost variable is not allowed in this context (because this is a ghost method or because the statement is guarded by a specification-only expression)
20 resolution/type errors detected in NonGhostQuantifiers.dfy

-------------------- AdvancedLHS.dfy --------------------
AdvancedLHS.dfy(31,23): Error: target object may be null
Execution trace:
    (0,0): anon0
    (0,0): anon15_Else

Dafny program verifier finished with 7 verified, 1 error

-------------------- ModulesCycle.dfy --------------------
ModulesCycle.dfy(3,9): Error: module T does not exist
ModulesCycle.dfy(6,7): Error: module definition contains a cycle (note: parent modules implicitly depend on submodules): A -> D -> C -> B
2 resolution/type errors detected in ModulesCycle.dfy

-------------------- Modules0.dfy --------------------
Modules0.dfy(5,8): Error: Duplicate name of top-level declaration: WazzupA
Modules0.dfy(6,11): Error: Duplicate name of top-level declaration: WazzupA
Modules0.dfy(7,7): Error: Duplicate name of top-level declaration: WazzupA
Modules0.dfy(10,7): Error: Duplicate name of top-level declaration: WazzupB
Modules0.dfy(11,8): Error: Duplicate name of top-level declaration: WazzupB
Modules0.dfy(12,11): Error: Duplicate name of top-level declaration: WazzupB
Modules0.dfy(53,18): Error: Undeclared top-level type or type parameter: MyClass1 (did you forget to qualify a name?)
Modules0.dfy(54,18): Error: Undeclared top-level type or type parameter: MyClass2 (did you forget to qualify a name?)
Modules0.dfy(65,18): Error: Undeclared top-level type or type parameter: MyClass2 (did you forget to qualify a name?)
Modules0.dfy(72,20): Error: Undeclared top-level type or type parameter: MyClass1 (did you forget to qualify a name?)
Modules0.dfy(72,34): Error: Undeclared top-level type or type parameter: MyClass0 (did you forget to qualify a name?)
Modules0.dfy(75,23): Error: Undeclared top-level type or type parameter: MyClass0 (did you forget to qualify a name?)
Modules0.dfy(80,24): Error: Undeclared top-level type or type parameter: MyClassY (did you forget to qualify a name?)
Modules0.dfy(89,16): Error: Undeclared top-level type or type parameter: ClassG (did you forget to qualify a name?)
Modules0.dfy(221,15): Error: Undeclared top-level type or type parameter: X (did you forget to qualify a name?)
Modules0.dfy(221,8): Error: new can be applied only to reference types (got X)
Modules0.dfy(230,13): Error: Undeclared type X in module B
Modules0.dfy(240,13): Error: unresolved identifier: X
Modules0.dfy(241,15): Error: member DoesNotExist does not exist in class X
Modules0.dfy(280,19): Error: Undeclared top-level type or type parameter: D (did you forget to qualify a name?)
Modules0.dfy(280,12): Error: new can be applied only to reference types (got D)
Modules0.dfy(283,25): Error: type of the receiver is not fully determined at this program point
Modules0.dfy(284,16): Error: type of the receiver is not fully determined at this program point
Modules0.dfy(284,6): Error: expected method call, found expression
Modules0.dfy(285,16): Error: type of the receiver is not fully determined at this program point
Modules0.dfy(285,6): Error: expected method call, found expression
Modules0.dfy(307,24): Error: module Q_Imp does not exist
Modules0.dfy(97,14): Error: Undeclared top-level type or type parameter: MyClassY (did you forget to qualify a name?)
28 resolution/type errors detected in Modules0.dfy

-------------------- Modules1.dfy --------------------
Modules1.dfy(76,16): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
Modules1.dfy(89,16): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
Modules1.dfy(91,18): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
Modules1.dfy(53,3): Error: decreases expression must be bounded below by 0
Execution trace:
    (0,0): anon0
Modules1.dfy(59,3): Error: failure to decrease termination measure
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 22 verified, 5 errors

-------------------- Modules2.dfy --------------------
Modules2.dfy(44,17): Error: The name C ambiguously refers to a type in one of the modules A, B (try qualifying the type name with the module name)
Modules2.dfy(44,10): Error: new can be applied only to reference types (got C)
Modules2.dfy(47,14): Error: the name 'E' denotes a datatype constructor, but does not do so uniquely; add an explicit qualification (for example, 'D.E')
Modules2.dfy(48,14): Error: The name D ambiguously refers to a type in one of the modules A, B
Modules2.dfy(50,11): Error: The name f ambiguously refers to a static member in one of the modules A, B
5 resolution/type errors detected in Modules2.dfy

-------------------- BadFunction.dfy --------------------
BadFunction.dfy(6,3): Error: failure to decrease termination measure
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else

Dafny program verifier finished with 2 verified, 1 error

-------------------- Comprehensions.dfy --------------------
Comprehensions.dfy(9,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon9_Then
    (0,0): anon10_Then
    (0,0): anon4
    (0,0): anon11_Then
    (0,0): anon12_Then
    (0,0): anon8

Dafny program verifier finished with 6 verified, 1 error

-------------------- Basics.dfy --------------------
Basics.dfy(42,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
Basics.dfy(66,42): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon13_Then
    (0,0): anon14_Then
    (0,0): anon15_Then
    Basics.dfy(66,72): anon16_Else
    Basics.dfy(66,82): anon17_Else
    Basics.dfy(66,95): anon18_Else
    (0,0): anon12
Basics.dfy(110,16): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon10_Then
Basics.dfy(129,10): Error: when left-hand sides 0 and 1 may refer to the same location, they must be assigned the same value
Execution trace:
    (0,0): anon0
    (0,0): anon10_Then
    (0,0): anon3
    (0,0): anon11_Then
    (0,0): anon6
    (0,0): anon12_Then
    (0,0): anon9
Basics.dfy(143,10): Error: when left-hand sides 0 and 1 refer to the same location, they must be assigned the same value
Execution trace:
    (0,0): anon0
Basics.dfy(155,19): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon11_Then
Basics.dfy(157,10): Error: assignment may update an object not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
    (0,0): anon3
Basics.dfy(157,10): Error: target object may be null
Execution trace:
    (0,0): anon0
    (0,0): anon3
Basics.dfy(162,12): Error: left-hand sides 0 and 1 may refer to the same location
Execution trace:
    (0,0): anon0
    (0,0): anon11_Then
    (0,0): anon3
    (0,0): anon12_Then
Basics.dfy(173,15): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon11_Then
    (0,0): anon3
    (0,0): anon12_Else
    (0,0): anon6
    (0,0): anon13_Then
    (0,0): anon8
    (0,0): anon14_Then
Basics.dfy(235,10): Error: when left-hand sides 0 and 1 refer to the same location, they must be assigned the same value
Execution trace:
    (0,0): anon0
Basics.dfy(426,12): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then
    (0,0): anon3
Basics.dfy(437,19): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
Basics.dfy(439,12): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then
    (0,0): anon3

Dafny program verifier finished with 61 verified, 14 errors

-------------------- ControlStructures.dfy --------------------
ControlStructures.dfy(5,3): Error: missing case in case statement: Purple
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
    (0,0): anon7_Else
    (0,0): anon8_Then
ControlStructures.dfy(5,3): Error: missing case in case statement: Blue
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
    (0,0): anon7_Else
    (0,0): anon8_Else
    (0,0): anon9_Then
ControlStructures.dfy(14,3): Error: missing case in case statement: Purple
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
    (0,0): anon7_Else
    (0,0): anon8_Then
ControlStructures.dfy(43,5): Error: missing case in case statement: Red
Execution trace:
    (0,0): anon0
    (0,0): anon8_Then
    (0,0): anon9_Else
    (0,0): anon10_Then
ControlStructures.dfy(51,3): Error: missing case in case statement: Red
Execution trace:
    (0,0): anon0
    (0,0): anon8_Else
    (0,0): anon9_Else
    (0,0): anon10_Else
    (0,0): anon11_Else
    (0,0): anon12_Then
ControlStructures.dfy(72,3): Error: alternative cases fail to cover all possibilties
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
ControlStructures.dfy(215,18): Error: assertion violation
Execution trace:
    (0,0): anon0
    ControlStructures.dfy(194,3): anon59_LoopHead
    (0,0): anon59_LoopBody
    ControlStructures.dfy(194,3): anon60_Else
    ControlStructures.dfy(194,3): anon61_Else
    ControlStructures.dfy(198,5): anon62_LoopHead
    (0,0): anon62_LoopBody
    ControlStructures.dfy(198,5): anon63_Else
    ControlStructures.dfy(198,5): anon64_Else
    (0,0): anon68_Then
    ControlStructures.dfy(210,9): anon69_LoopHead
    (0,0): anon69_LoopBody
    ControlStructures.dfy(210,9): anon70_Else
    (0,0): anon71_Then
ControlStructures.dfy(232,21): Error: assertion violation
Execution trace:
    (0,0): anon0
    ControlStructures.dfy(194,3): anon59_LoopHead
    (0,0): anon59_LoopBody
    ControlStructures.dfy(194,3): anon60_Else
    ControlStructures.dfy(194,3): anon61_Else
    ControlStructures.dfy(198,5): anon62_LoopHead
    (0,0): anon62_LoopBody
    ControlStructures.dfy(198,5): anon63_Else
    ControlStructures.dfy(198,5): anon64_Else
    (0,0): anon68_Then
    ControlStructures.dfy(210,9): anon69_LoopHead
    (0,0): anon69_LoopBody
    ControlStructures.dfy(210,9): anon70_Else
    ControlStructures.dfy(210,9): anon71_Else
    (0,0): anon72_Then
    (0,0): after_4
    ControlStructures.dfy(221,7): anon74_LoopHead
    (0,0): anon74_LoopBody
    ControlStructures.dfy(221,7): anon75_Else
    ControlStructures.dfy(221,7): anon76_Else
    (0,0): anon78_Then
    (0,0): anon38
    (0,0): anon83_Then
    (0,0): anon52
ControlStructures.dfy(235,30): Error: assertion violation
Execution trace:
    (0,0): anon0
    ControlStructures.dfy(194,3): anon59_LoopHead
    (0,0): anon59_LoopBody
    ControlStructures.dfy(194,3): anon60_Else
    ControlStructures.dfy(194,3): anon61_Else
    ControlStructures.dfy(198,5): anon62_LoopHead
    (0,0): anon62_LoopBody
    ControlStructures.dfy(198,5): anon63_Else
    ControlStructures.dfy(198,5): anon64_Else
    (0,0): anon65_Then
    (0,0): anon84_Then
    (0,0): anon85_Then
    (0,0): anon56
ControlStructures.dfy(238,17): Error: assertion violation
Execution trace:
    (0,0): anon0
    ControlStructures.dfy(194,3): anon59_LoopHead
    (0,0): anon59_LoopBody
    ControlStructures.dfy(194,3): anon60_Else
    ControlStructures.dfy(194,3): anon61_Else
    ControlStructures.dfy(198,5): anon62_LoopHead
    (0,0): anon62_LoopBody
    ControlStructures.dfy(198,5): anon63_Else
    ControlStructures.dfy(198,5): anon64_Else
    (0,0): anon68_Then
    ControlStructures.dfy(210,9): anon69_LoopHead
    (0,0): anon69_LoopBody
    ControlStructures.dfy(210,9): anon70_Else
    ControlStructures.dfy(210,9): anon71_Else
    (0,0): anon72_Then
    (0,0): after_4
    ControlStructures.dfy(221,7): anon74_LoopHead
    (0,0): anon74_LoopBody
    ControlStructures.dfy(221,7): anon75_Else
    ControlStructures.dfy(221,7): anon76_Else
    (0,0): anon79_Then
    (0,0): anon82_Then
    (0,0): anon86_Then
    (0,0): anon58

Dafny program verifier finished with 22 verified, 10 errors

-------------------- Termination.dfy --------------------
Termination.dfy(356,47): Error: failure to decrease termination measure
Execution trace:
    (0,0): anon0
    (0,0): anon7_Else
    (0,0): anon8_Then
    (0,0): anon9_Else
Termination.dfy(105,3): Error: cannot prove termination; try supplying a decreases clause for the loop
Execution trace:
    (0,0): anon0
    Termination.dfy(105,3): anon6_LoopHead
    (0,0): anon6_LoopBody
    Termination.dfy(105,3): anon7_Else
    Termination.dfy(105,3): anon8_Else
Termination.dfy(113,3): Error: cannot prove termination; try supplying a decreases clause for the loop
Execution trace:
    (0,0): anon0
    Termination.dfy(113,3): anon8_LoopHead
    (0,0): anon8_LoopBody
    Termination.dfy(113,3): anon9_Else
    (0,0): anon10_Then
    (0,0): anon5
    Termination.dfy(113,3): anon11_Else
Termination.dfy(122,3): Error: decreases expression might not decrease
Execution trace:
    (0,0): anon0
    Termination.dfy(122,3): anon8_LoopHead
    (0,0): anon8_LoopBody
    Termination.dfy(122,3): anon9_Else
    (0,0): anon10_Then
    (0,0): anon5
    Termination.dfy(122,3): anon11_Else
Termination.dfy(123,17): Error: decreases expression must be bounded below by 0 at end of loop iteration
Execution trace:
    (0,0): anon0
    Termination.dfy(122,3): anon8_LoopHead
    (0,0): anon8_LoopBody
    Termination.dfy(122,3): anon9_Else
    (0,0): anon10_Then
    (0,0): anon5
    Termination.dfy(122,3): anon11_Else
Termination.dfy(251,35): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
    (0,0): anon7_Else
    (0,0): anon8_Then
Termination.dfy(291,3): Error: decreases expression might not decrease
Execution trace:
    Termination.dfy(291,3): anon9_LoopHead
    (0,0): anon9_LoopBody
    Termination.dfy(291,3): anon10_Else
    Termination.dfy(291,3): anon11_Else
    (0,0): anon12_Else

Dafny program verifier finished with 59 verified, 7 errors

-------------------- DTypes.dfy --------------------
DTypes.dfy(15,14): Error: assertion violation
Execution trace:
    (0,0): anon0
DTypes.dfy(53,18): Error: assertion violation
Execution trace:
    (0,0): anon0
DTypes.dfy(117,13): Error: assertion violation
DTypes.dfy(89,30): Related location
Execution trace:
    (0,0): anon0
DTypes.dfy(123,13): Error: assertion violation
DTypes.dfy(89,20): Related location
Execution trace:
    (0,0): anon0
DTypes.dfy(133,12): Error: assertion violation
DTypes.dfy(128,6): Related location
DTypes.dfy(89,20): Related location
Execution trace:
    (0,0): anon0
DTypes.dfy(154,12): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon6_Then
    (0,0): anon4

Dafny program verifier finished with 27 verified, 6 errors

-------------------- ParallelResolveErrors.dfy --------------------
ParallelResolveErrors.dfy(7,9): Error: Assignment to non-ghost field is not allowed in this context (because this is a ghost method or because the statement is guarded by a specification-only expression)
ParallelResolveErrors.dfy(18,6): Error: LHS of assignment must denote a mutable variable or field
ParallelResolveErrors.dfy(23,6): Error: body of forall statement is attempting to update a variable declared outside the forall statement
ParallelResolveErrors.dfy(41,6): Error: Assignment to non-ghost variable is not allowed in this context (because this is a ghost method or because the statement is guarded by a specification-only expression)
ParallelResolveErrors.dfy(53,13): Error: new allocation not supported in forall statements
ParallelResolveErrors.dfy(58,13): Error: new allocation not allowed in ghost context
ParallelResolveErrors.dfy(59,13): Error: new allocation not allowed in ghost context
ParallelResolveErrors.dfy(60,13): Error: new allocation not allowed in ghost context
ParallelResolveErrors.dfy(61,13): Error: new allocation not allowed in ghost context
ParallelResolveErrors.dfy(62,6): Error: the body of the enclosing forall statement is not allowed to update heap locations, so any call must be to a method with an empty modifies clause
ParallelResolveErrors.dfy(63,6): Error: the body of the enclosing forall statement is not allowed to call non-ghost methods
ParallelResolveErrors.dfy(70,19): Error: trying to break out of more loop levels than there are enclosing loops
ParallelResolveErrors.dfy(74,18): Error: return statement is not allowed inside a forall statement
ParallelResolveErrors.dfy(81,21): Error: trying to break out of more loop levels than there are enclosing loops
ParallelResolveErrors.dfy(82,20): Error: trying to break out of more loop levels than there are enclosing loops
ParallelResolveErrors.dfy(83,20): Error: break label is undefined or not in scope: OutsideLoop
ParallelResolveErrors.dfy(92,24): Error: trying to break out of more loop levels than there are enclosing loops
ParallelResolveErrors.dfy(93,24): Error: break label is undefined or not in scope: OutsideLoop
ParallelResolveErrors.dfy(104,9): Error: the body of the enclosing forall statement is not allowed to update heap locations
ParallelResolveErrors.dfy(112,6): Error: the body of the enclosing forall statement is not allowed to update heap locations, so any call must be to a method with an empty modifies clause
ParallelResolveErrors.dfy(117,6): Error: the body of the enclosing forall statement is not allowed to update heap locations, so any call must be to a method with an empty modifies clause
21 resolution/type errors detected in ParallelResolveErrors.dfy

-------------------- Parallel.dfy --------------------
Parallel.dfy(31,5): Error BP5002: A precondition for this call might not hold.
Parallel.dfy(57,14): Related location: This is the precondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon29_Else
    (0,0): anon32_Else
    (0,0): anon33_Then
    (0,0): anon34_Then
    (0,0): anon35_Then
    (0,0): anon14
Parallel.dfy(35,5): Error: target object may be null
Execution trace:
    (0,0): anon0
    (0,0): anon29_Else
    (0,0): anon32_Else
    (0,0): anon33_Else
    (0,0): anon36_Then
    (0,0): anon37_Then
    (0,0): anon38_Then
    (0,0): anon20
Parallel.dfy(39,18): Error: possible violation of postcondition of forall statement
Execution trace:
    (0,0): anon0
    (0,0): anon29_Else
    (0,0): anon32_Else
    (0,0): anon33_Else
    (0,0): anon36_Else
    (0,0): anon39_Then
    (0,0): anon40_Then
    (0,0): anon26
Parallel.dfy(44,19): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon29_Else
    (0,0): anon32_Else
    (0,0): anon33_Else
    (0,0): anon36_Else
    (0,0): anon39_Then
    (0,0): anon40_Then
Parallel.dfy(90,19): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon10_Else
    (0,0): anon11_Then
Parallel.dfy(96,20): Error: possible violation of postcondition of forall statement
Execution trace:
    (0,0): anon0
    (0,0): anon10_Else
    (0,0): anon11_Then
    (0,0): anon12_Then
Parallel.dfy(119,12): Error: value assigned to a nat must be non-negative
Execution trace:
    (0,0): anon0
    (0,0): anon6_Then
    (0,0): anon7_Then
    (0,0): anon3
Parallel.dfy(182,12): Error: left-hand sides for different forall-statement bound variables may refer to the same location
Execution trace:
    (0,0): anon0
    (0,0): anon19_Then
    (0,0): anon20_Then
    (0,0): anon5
Parallel.dfy(293,10): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else

Dafny program verifier finished with 43 verified, 9 errors

-------------------- TypeParameters.dfy --------------------
TypeParameters.dfy(44,22): Error: assertion violation
Execution trace:
    (0,0): anon0
TypeParameters.dfy(66,27): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
    (0,0): anon2
TypeParameters.dfy(153,12): Error: assertion violation
TypeParameters.dfy(153,28): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon20_Then
    TypeParameters.dfy(153,32): anon21_Else
    (0,0): anon5
TypeParameters.dfy(155,12): Error: assertion violation
TypeParameters.dfy(155,33): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon23_Then
    TypeParameters.dfy(155,37): anon24_Else
    (0,0): anon11
TypeParameters.dfy(157,12): Error: assertion violation
TypeParameters.dfy(157,20): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon25_Then
TypeParameters.dfy(159,12): Error: assertion violation
TypeParameters.dfy(144,5): Related location
TypeParameters.dfy(159,21): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon26_Then
TypeParameters.dfy(161,12): Error: assertion violation
TypeParameters.dfy(146,8): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon27_Then
TypeParameters.dfy(175,15): Error BP5005: This loop invariant might not be maintained by the loop.
TypeParameters.dfy(175,38): Related location
Execution trace:
    (0,0): anon0
    TypeParameters.dfy(168,3): anon16_LoopHead
    (0,0): anon16_LoopBody
    TypeParameters.dfy(168,3): anon17_Else
    (0,0): anon19_Then
    TypeParameters.dfy(174,3): anon20_LoopHead
    (0,0): anon20_LoopBody
    TypeParameters.dfy(174,3): anon21_Else
    TypeParameters.dfy(174,3): anon23_Else

Dafny program verifier finished with 50 verified, 8 errors

-------------------- Datatypes.dfy --------------------
Datatypes.dfy(294,10): Error BP5003: A postcondition might not hold on this return path.
Datatypes.dfy(292,15): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon13_Then
    (0,0): anon14_Else
    (0,0): anon15_Then
    (0,0): anon6
Datatypes.dfy(295,12): Error: missing case in case statement: Appendix
Execution trace:
    (0,0): anon0
    (0,0): anon13_Then
    (0,0): anon14_Else
    (0,0): anon15_Else
    (0,0): anon16_Then
Datatypes.dfy(346,5): Error: missing case in case statement: Cons
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
    (0,0): anon7_Then
Datatypes.dfy(346,5): Error: missing case in case statement: Nil
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
    (0,0): anon7_Else
    (0,0): anon8_Then
Datatypes.dfy(353,8): Error: missing case in case statement: Cons
Execution trace:
    (0,0): anon0
    (0,0): anon9_Else
    (0,0): anon10_Then
    (0,0): anon11_Then
Datatypes.dfy(353,8): Error: missing case in case statement: Nil
Execution trace:
    (0,0): anon0
    (0,0): anon9_Else
    (0,0): anon10_Then
    (0,0): anon11_Else
    (0,0): anon12_Then
Datatypes.dfy(79,20): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon20_Else
    (0,0): anon21_Then
    (0,0): anon4
    (0,0): anon22_Else
    (0,0): anon23_Then
    (0,0): anon24_Else
    (0,0): anon25_Then
Datatypes.dfy(167,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then
Datatypes.dfy(169,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
    (0,0): anon5_Then
Datatypes.dfy(198,13): Error: destructor 'Car' can only be applied to datatype values constructed by 'XCons'
Execution trace:
    (0,0): anon0
Datatypes.dfy(201,17): Error: destructor 'Car' can only be applied to datatype values constructed by 'XCons'
Execution trace:
    (0,0): anon0
    (0,0): anon6_Then
Datatypes.dfy(222,17): Error: destructor 'c' can only be applied to datatype values constructed by 'T''
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then

Dafny program verifier finished with 44 verified, 12 errors

-------------------- StatementExpressions.dfy --------------------
StatementExpressions.dfy(52,11): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon6_Then
    (0,0): anon8_Then
StatementExpressions.dfy(56,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon6_Then
    StatementExpressions.dfy(50,7): anon8_Else
StatementExpressions.dfy(74,6): Error: possible division by zero
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
StatementExpressions.dfy(85,5): Error: value assigned to a nat must be non-negative
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
StatementExpressions.dfy(95,11): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon6_Then

Dafny program verifier finished with 17 verified, 5 errors

-------------------- Coinductive.dfy --------------------
Coinductive.dfy(10,11): Error: because of cyclic dependencies among constructor argument types, no instances of datatype 'Rec_Forever' can be constructed
Coinductive.dfy(13,11): Error: because of cyclic dependencies among constructor argument types, no instances of datatype 'D' can be constructed
Coinductive.dfy(35,11): Error: because of cyclic dependencies among constructor argument types, no instances of datatype 'K' can be constructed
Coinductive.dfy(61,11): Error: because of cyclic dependencies among constructor argument types, no instances of datatype 'NotFiniteEnough_Dt' can be constructed
Coinductive.dfy(90,8): Error: a copredicate can be called recursively only in positive positions
Coinductive.dfy(91,8): Error: a copredicate can be called recursively only in positive positions
Coinductive.dfy(92,8): Error: a copredicate can be called recursively only in positive positions and cannot sit inside an unbounded existential quantifier
Coinductive.dfy(92,21): Error: a copredicate can be called recursively only in positive positions and cannot sit inside an unbounded existential quantifier
Coinductive.dfy(98,5): Error: a copredicate can be called recursively only in positive positions
Coinductive.dfy(101,27): Error: a copredicate can be called recursively only in positive positions and cannot sit inside an unbounded existential quantifier
Coinductive.dfy(102,28): Error: a copredicate can be called recursively only in positive positions and cannot sit inside an unbounded existential quantifier
Coinductive.dfy(103,17): Error: a copredicate can be called recursively only in positive positions and cannot sit inside an unbounded existential quantifier
Coinductive.dfy(113,24): Error: a copredicate can be called recursively only in positive positions and cannot sit inside an unbounded existential quantifier
Coinductive.dfy(119,15): Error: a copredicate can be called recursively only in positive positions and cannot sit inside an unbounded existential quantifier
Coinductive.dfy(120,10): Error: a copredicate can be called recursively only in positive positions and cannot sit inside an unbounded existential quantifier
15 resolution/type errors detected in Coinductive.dfy

-------------------- Corecursion.dfy --------------------
Corecursion.dfy(15,13): Error: cannot prove termination; try supplying a decreases clause (note that only functions without side effects can be called co-recursively)
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
Corecursion.dfy(21,13): Error: cannot prove termination; try supplying a decreases clause (note that only functions without any ensures clause can be called co-recursively)
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
Corecursion.dfy(56,5): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
Corecursion.dfy(69,16): Error: cannot prove termination; try supplying a decreases clause (note that calls cannot be co-recursive in this context)
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
Corecursion.dfy(91,15): Error: cannot prove termination; try supplying a decreases clause (note that a call can be co-recursive only if all intra-cluster calls are in non-destructive contexts)
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Then
Corecursion.dfy(101,15): Error: cannot prove termination; try supplying a decreases clause (note that a call can be co-recursive only if all intra-cluster calls are in non-destructive contexts)
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Then

Dafny program verifier finished with 10 verified, 6 errors

-------------------- CoResolution.dfy --------------------
CoResolution.dfy(14,9): Error: member Undeclared# does not exist in class _default
CoResolution.dfy(15,4): Error: unresolved identifier: Undeclared#
CoResolution.dfy(18,7): Error: unresolved identifier: _k
CoResolution.dfy(36,8): Error: == can only be applied to expressions of types that support equality (got Stream<_T0>)
CoResolution.dfy(47,8): Error: Assignment to non-ghost variable is not allowed in this context (because this is a ghost method or because the statement is guarded by a specification-only expression)
CoResolution.dfy(64,10): Error: a copredicate is not allowed to declare any reads clause
CoResolution.dfy(70,31): Error: a copredicate is not allowed to declare any ensures clause
CoResolution.dfy(79,20): Error: a recursive call from a copredicate can go only to other copredicates
CoResolution.dfy(83,20): Error: a recursive call from a copredicate can go only to other copredicates
CoResolution.dfy(92,4): Error: a recursive call from a comethod can go only to other comethods and prefix methods
CoResolution.dfy(106,13): Error: a recursive call from a comethod can go only to other comethods and prefix methods
CoResolution.dfy(107,13): Error: a recursive call from a comethod can go only to other comethods and prefix methods
CoResolution.dfy(126,13): Error: a recursive call from a comethod can go only to other comethods and prefix methods
CoResolution.dfy(127,13): Error: a recursive call from a comethod can go only to other comethods and prefix methods
CoResolution.dfy(146,4): Error: a recursive call from a copredicate can go only to other copredicates
CoResolution.dfy(148,4): Error: a recursive call from a copredicate can go only to other copredicates
16 resolution/type errors detected in CoResolution.dfy

-------------------- CoPrefix.dfy --------------------
CoPrefix.dfy(161,3): Error BP5003: A postcondition might not hold on this return path.
CoPrefix.dfy(160,15): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
CoPrefix.dfy(166,3): Error BP5003: A postcondition might not hold on this return path.
CoPrefix.dfy(165,15): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
CoPrefix.dfy(173,5): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
CoPrefix.dfy(60,7): Error: failure to decrease termination measure
Execution trace:
    (0,0): anon0
    (0,0): anon7_Then
    (0,0): anon8_Else
    (0,0): anon9_Then
CoPrefix.dfy(73,7): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon7_Then
    (0,0): anon8_Else
    (0,0): anon9_Then
CoPrefix.dfy(111,1): Error BP5003: A postcondition might not hold on this return path.
CoPrefix.dfy(110,11): Related location: This is the postcondition that might not hold.
CoPrefix.dfy(98,17): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
CoPrefix.dfy(135,25): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon9_Then
    (0,0): anon10_Then
CoPrefix.dfy(139,25): Error: assertion violation
CoPrefix.dfy(114,23): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon9_Then
    (0,0): anon12_Then
CoPrefix.dfy(148,1): Error BP5003: A postcondition might not hold on this return path.
CoPrefix.dfy(147,11): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else

Dafny program verifier finished with 41 verified, 9 errors

-------------------- CoinductiveProofs.dfy --------------------
CoinductiveProofs.dfy(26,12): Error: assertion violation
CoinductiveProofs.dfy(10,17): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon6_Then
CoinductiveProofs.dfy(56,1): Error BP5003: A postcondition might not hold on this return path.
CoinductiveProofs.dfy(55,11): Related location: This is the postcondition that might not hold.
CoinductiveProofs.dfy(51,3): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
CoinductiveProofs.dfy(71,12): Error: assertion violation
CoinductiveProofs.dfy(51,3): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon6_Then
CoinductiveProofs.dfy(88,1): Error BP5003: A postcondition might not hold on this return path.
CoinductiveProofs.dfy(87,11): Related location: This is the postcondition that might not hold.
CoinductiveProofs.dfy(77,3): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
CoinductiveProofs.dfy(97,12): Error: assertion violation
CoinductiveProofs.dfy(77,3): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon6_Then
CoinductiveProofs.dfy(108,1): Error BP5003: A postcondition might not hold on this return path.
CoinductiveProofs.dfy(107,11): Related location: This is the postcondition that might not hold.
CoinductiveProofs.dfy(103,3): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
CoinductiveProofs.dfy(147,1): Error BP5003: A postcondition might not hold on this return path.
CoinductiveProofs.dfy(146,22): Related location: This is the postcondition that might not hold.
CoinductiveProofs.dfy(1,24): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
CoinductiveProofs.dfy(153,1): Error BP5003: A postcondition might not hold on this return path.
CoinductiveProofs.dfy(152,22): Related location: This is the postcondition that might not hold.
CoinductiveProofs.dfy(1,24): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then

Dafny program verifier finished with 35 verified, 8 errors

-------------------- TypeAntecedents.dfy --------------------
TypeAntecedents.dfy(32,13): Error: assertion violation
Execution trace:
    (0,0): anon0
TypeAntecedents.dfy(55,1): Error BP5003: A postcondition might not hold on this return path.
TypeAntecedents.dfy(54,15): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon25_Then
    (0,0): anon6
    (0,0): anon28_Then
    (0,0): anon8
    (0,0): anon29_Else
    (0,0): anon31_Else
    (0,0): anon33_Then
    (0,0): anon20
    (0,0): anon34_Then
    (0,0): anon35_Then
    (0,0): anon24
TypeAntecedents.dfy(63,16): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon25_Else
    (0,0): anon26_Then
    (0,0): anon27_Else

Dafny program verifier finished with 12 verified, 3 errors

-------------------- NoTypeArgs.dfy --------------------

Dafny program verifier finished with 15 verified, 0 errors

-------------------- EqualityTypes.dfy --------------------
EqualityTypes.dfy(31,13): Error: a type declaration that requires equality support cannot be replaced by a codatatype
EqualityTypes.dfy(32,11): Error: datatype 'Y' is used to refine an arbitrary type with equality support, but 'Y' does not support equality
EqualityTypes.dfy(37,11): Error: arbitrary type 'X' is not allowed to be replaced by a datatype that takes a different number of type parameters
EqualityTypes.dfy(38,8): Error: arbitrary type 'Y' is not allowed to be replaced by a class that takes a different number of type parameters
EqualityTypes.dfy(42,11): Error: datatype 'X' is used to refine an arbitrary type with equality support, but 'X' does not support equality
EqualityTypes.dfy(43,11): Error: datatype 'Y' is used to refine an arbitrary type with equality support, but 'Y' does not support equality
EqualityTypes.dfy(63,7): Error: == can only be applied to expressions of types that support equality (got Dt<T>)
EqualityTypes.dfy(82,8): Error: type parameter 0 (T) passed to method M must support equality (got _T0)
EqualityTypes.dfy(106,7): Error: == can only be applied to expressions of types that support equality (got D)
EqualityTypes.dfy(111,13): Error: == can only be applied to expressions of types that support equality (got D)
EqualityTypes.dfy(115,16): Error: == can only be applied to expressions of types that support equality (got D)
11 resolution/type errors detected in EqualityTypes.dfy

-------------------- SplitExpr.dfy --------------------
SplitExpr.dfy(89,15): Error: loop invariant violation
SplitExpr.dfy(83,44): Related location
Execution trace:
    SplitExpr.dfy(88,3): anon7_LoopHead

Dafny program verifier finished with 10 verified, 1 error

-------------------- LoopModifies.dfy --------------------
LoopModifies.dfy(6,5): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
LoopModifies.dfy(17,8): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
    LoopModifies.dfy(14,4): anon8_LoopHead
    (0,0): anon8_LoopBody
    LoopModifies.dfy(14,4): anon9_Else
    LoopModifies.dfy(14,4): anon11_Else
LoopModifies.dfy(46,8): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
    LoopModifies.dfy(42,4): anon8_LoopHead
    (0,0): anon8_LoopBody
    LoopModifies.dfy(42,4): anon9_Else
    LoopModifies.dfy(42,4): anon11_Else
LoopModifies.dfy(61,8): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
    LoopModifies.dfy(57,4): anon9_LoopHead
    (0,0): anon9_LoopBody
    LoopModifies.dfy(57,4): anon10_Else
    LoopModifies.dfy(57,4): anon12_Else
LoopModifies.dfy(74,4): Error: loop modifies clause may violate context's modifies clause
Execution trace:
    (0,0): anon0
LoopModifies.dfy(98,8): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
    LoopModifies.dfy(90,4): anon8_LoopHead
    (0,0): anon8_LoopBody
    LoopModifies.dfy(90,4): anon9_Else
    LoopModifies.dfy(90,4): anon11_Else
LoopModifies.dfy(146,11): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
    LoopModifies.dfy(134,4): anon17_LoopHead
    (0,0): anon17_LoopBody
    LoopModifies.dfy(134,4): anon18_Else
    LoopModifies.dfy(134,4): anon20_Else
    LoopModifies.dfy(139,7): anon21_LoopHead
    (0,0): anon21_LoopBody
    LoopModifies.dfy(139,7): anon22_Else
    LoopModifies.dfy(139,7): anon24_Else
LoopModifies.dfy(197,10): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
    LoopModifies.dfy(193,4): anon8_LoopHead
    (0,0): anon8_LoopBody
    LoopModifies.dfy(193,4): anon9_Else
    LoopModifies.dfy(193,4): anon11_Else
LoopModifies.dfy(285,13): Error: assignment may update an array element not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
    LoopModifies.dfy(273,4): anon16_LoopHead
    (0,0): anon16_LoopBody
    LoopModifies.dfy(273,4): anon17_Else
    LoopModifies.dfy(273,4): anon19_Else
    LoopModifies.dfy(281,7): anon20_LoopHead
    (0,0): anon20_LoopBody
    LoopModifies.dfy(281,7): anon21_Else
    LoopModifies.dfy(281,7): anon23_Else

Dafny program verifier finished with 23 verified, 9 errors

-------------------- Refinement.dfy --------------------
Refinement.dfy(12,5): Error BP5003: A postcondition might not hold on this return path.
Refinement.dfy(11,17): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
Refinement.dfy[B](12,5): Error BP5003: A postcondition might not hold on this return path.
Refinement.dfy(30,20): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
Refinement.dfy(61,14): Error: assertion violation
Execution trace:
    (0,0): anon0
Refinement.dfy(71,17): Error: assertion violation
Execution trace:
    (0,0): anon0
Refinement.dfy(90,12): Error BP5003: A postcondition might not hold on this return path.
Refinement.dfy(69,15): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
Refinement.dfy(93,3): Error BP5003: A postcondition might not hold on this return path.
Refinement.dfy(74,15): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
Refinement.dfy(180,5): Error BP5003: A postcondition might not hold on this return path.
Refinement.dfy[IncorrectConcrete](112,15): Related location: This is the postcondition that might not hold.
Refinement.dfy(177,9): Related location
Execution trace:
    (0,0): anon0
Refinement.dfy(184,5): Error BP5003: A postcondition might not hold on this return path.
Refinement.dfy[IncorrectConcrete](120,15): Related location: This is the postcondition that might not hold.
Refinement.dfy(177,9): Related location
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then
    (0,0): anon3
Refinement.dfy(190,7): Error: assertion violation
Refinement.dfy[IncorrectConcrete](128,24): Related location
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 48 verified, 9 errors

-------------------- RefinementErrors.dfy --------------------
RefinementErrors.dfy(27,17): Error: a refining method is not allowed to add preconditions
RefinementErrors.dfy(28,15): Error: a refining method is not allowed to extend the modifies clause
RefinementErrors.dfy(31,14): Error: a predicate declaration (abc) can only refine a predicate
RefinementErrors.dfy(32,8): Error: a field re-declaration (xyz) must be to ghostify the field
RefinementErrors.dfy(34,13): Error: a function method cannot be changed into a (ghost) function in a refining module: F
RefinementErrors.dfy(35,9): Error: type parameters are not allowed to be renamed from the names given in the function in the module being refined (expected 'A', found 'C')
RefinementErrors.dfy(35,11): Error: type parameters are not allowed to be renamed from the names given in the function in the module being refined (expected 'B', found 'A')
RefinementErrors.dfy(35,13): Error: type parameters are not allowed to be renamed from the names given in the function in the module being refined (expected 'C', found 'B')
RefinementErrors.dfy(36,23): Error: the type of parameter 'z' is different from the type of the same parameter in the corresponding function in the module it refines ('seq<C>' instead of 'set<C>')
RefinementErrors.dfy(37,9): Error: there is a difference in name of parameter 3 ('k' versus 'b') of function F compared to corresponding function in the module it refines
RefinementErrors.dfy(54,20): Error: a function can be changed into a function method in a refining module only if the function has not yet been given a body: G
11 resolution/type errors detected in RefinementErrors.dfy

-------------------- ReturnErrors.dfy --------------------
ReturnErrors.dfy(30,10): Error: cannot have method call in return statement.
ReturnErrors.dfy(36,10): Error: cannot have effectful parameter in multi-return statement.
ReturnErrors.dfy(41,10): Error: can only have initialization methods which modify at most 'this'.
3 resolution/type errors detected in ReturnErrors.dfy

-------------------- ReturnTests.dfy --------------------

Dafny program verifier finished with 20 verified, 0 errors

-------------------- ChainingDisjointTests.dfy --------------------

Dafny program verifier finished with 6 verified, 0 errors

-------------------- CallStmtTests.dfy --------------------
CallStmtTests.dfy(4,3): Error: LHS of assignment must denote a mutable variable
CallStmtTests.dfy(15,8): Error: actual out-parameter 0 is required to be a ghost variable
2 resolution/type errors detected in CallStmtTests.dfy

-------------------- MultiSets.dfy --------------------
MultiSets.dfy(157,3): Error BP5003: A postcondition might not hold on this return path.
MultiSets.dfy(156,15): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
MultiSets.dfy(163,3): Error BP5003: A postcondition might not hold on this return path.
MultiSets.dfy(162,15): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
MultiSets.dfy(176,11): Error: new number of occurrences might be negative
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then
    (0,0): anon3
MultiSets.dfy(267,24): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon11_Then
    (0,0): anon3
    (0,0): anon12_Then
    (0,0): anon14_Else

Dafny program verifier finished with 54 verified, 4 errors

-------------------- PredExpr.dfy --------------------
PredExpr.dfy(4,12): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
PredExpr.dfy(36,15): Error: value assigned to a nat must be non-negative
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Else
PredExpr.dfy(49,17): Error: assertion violation
Execution trace:
    (0,0): anon0
PredExpr.dfy(74,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon8_Else
    (0,0): anon3
    PredExpr.dfy(73,20): anon10_Else
    (0,0): anon6

Dafny program verifier finished with 11 verified, 4 errors

-------------------- Predicates.dfy --------------------
Predicates.dfy[B](18,5): Error BP5003: A postcondition might not hold on this return path.
Predicates.dfy[B](17,15): Related location: This is the postcondition that might not hold.
Predicates.dfy(28,9): Related location
Execution trace:
    (0,0): anon0
Predicates.dfy(85,16): Error: assertion violation
Execution trace:
    (0,0): anon0
Predicates.dfy(89,14): Error: assertion violation
Execution trace:
    (0,0): anon0
Predicates.dfy[Tricky_Full](123,5): Error BP5003: A postcondition might not hold on this return path.
Predicates.dfy[Tricky_Full](122,15): Related location: This is the postcondition that might not hold.
Predicates.dfy(133,7): Related location
Predicates.dfy[Tricky_Full](113,9): Related location
Execution trace:
    (0,0): anon0
Predicates.dfy(161,5): Error BP5003: A postcondition might not hold on this return path.
Predicates.dfy(160,15): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
Predicates.dfy[Q1](151,5): Error BP5003: A postcondition might not hold on this return path.
Predicates.dfy[Q1](150,15): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 52 verified, 6 errors

-------------------- Skeletons.dfy --------------------
Skeletons.dfy(42,3): Error BP5003: A postcondition might not hold on this return path.
Skeletons.dfy(41,15): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    Skeletons.dfy[C0](29,5): anon11_LoopHead
    (0,0): anon11_LoopBody
    Skeletons.dfy[C0](29,5): anon12_Else
    (0,0): anon13_Then
    Skeletons.dfy[C0](34,19): anon15_Else
    (0,0): anon10

Dafny program verifier finished with 9 verified, 1 error

-------------------- OpaqueFunctions.dfy --------------------
OpaqueFunctions.dfy(24,16): Error: assertion violation
Execution trace:
    (0,0): anon0
OpaqueFunctions.dfy(49,7): Error BP5002: A precondition for this call might not hold.
OpaqueFunctions.dfy(21,16): Related location: This is the precondition that might not hold.
Execution trace:
    (0,0): anon0
OpaqueFunctions.dfy(55,20): Error: assertion violation
Execution trace:
    (0,0): anon0
OpaqueFunctions.dfy(57,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
OpaqueFunctions.dfy(60,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon6_Then
OpaqueFunctions.dfy(63,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
OpaqueFunctions.dfy(74,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
OpaqueFunctions.dfy(76,9): Error BP5002: A precondition for this call might not hold.
OpaqueFunctions.dfy[A'](21,16): Related location: This is the precondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
OpaqueFunctions.dfy(83,20): Error: assertion violation
Execution trace:
    (0,0): anon0
OpaqueFunctions.dfy(85,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
OpaqueFunctions.dfy(88,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon6_Then
OpaqueFunctions.dfy(91,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
OpaqueFunctions.dfy(102,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
OpaqueFunctions.dfy(104,9): Error BP5002: A precondition for this call might not hold.
OpaqueFunctions.dfy[A'](21,16): Related location: This is the precondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
OpaqueFunctions.dfy(111,20): Error: assertion violation
Execution trace:
    (0,0): anon0
OpaqueFunctions.dfy(113,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
OpaqueFunctions.dfy(116,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon6_Then
OpaqueFunctions.dfy(119,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
OpaqueFunctions.dfy(135,12): Error: assertion violation
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 41 verified, 19 errors

-------------------- Maps.dfy --------------------
Maps.dfy(76,8): Error: element may not be in domain
Execution trace:
    (0,0): anon0
Maps.dfy(126,13): Error: assertion violation
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 32 verified, 2 errors

-------------------- LiberalEquality.dfy --------------------
LiberalEquality.dfy(18,14): Error: arguments must have the same type (got T and U)
LiberalEquality.dfy(37,14): Error: arguments must have the same type (got Weird<T,int,V> and Weird<T,bool,V>)
LiberalEquality.dfy(52,14): Error: arguments must have the same type (got array<int> and array<bool>)
3 resolution/type errors detected in LiberalEquality.dfy

-------------------- RefinementModificationChecking.dfy --------------------
RefinementModificationChecking.dfy(17,4): Error: cannot assign to variable defined previously
RefinementModificationChecking.dfy(18,4): Error: cannot assign to variable defined previously
2 resolution/type errors detected in RefinementModificationChecking.dfy

-------------------- TailCalls.dfy --------------------
TailCalls.dfy(18,15): Error: this recursive call is not recognized as being tail recursive, because it is followed by non-ghost code
TailCalls.dfy(30,12): Error: 'decreases *' is allowed only on tail-recursive methods
TailCalls.dfy(37,12): Error: 'decreases *' is allowed only on tail-recursive methods
TailCalls.dfy(42,12): Error: 'decreases *' is allowed only on tail-recursive methods
TailCalls.dfy(64,12): Error: 'decreases *' is allowed only on tail-recursive methods
5 resolution/type errors detected in TailCalls.dfy

-------------------- IteratorResolution.dfy --------------------
IteratorResolution.dfy(59,11): Error: LHS of assignment does not denote a mutable field
IteratorResolution.dfy(64,18): Error: arguments must have the same type (got _T0 and int)
IteratorResolution.dfy(76,19): Error: RHS (of type bool) not assignable to LHS (of type int)
IteratorResolution.dfy(79,13): Error: when allocating an object of type 'GenericIteratorResult', one of its constructor methods must be called
IteratorResolution.dfy(83,15): Error: logical negation expects a boolean argument (instead got int)
IteratorResolution.dfy(17,11): Error: LHS of assignment does not denote a mutable field
IteratorResolution.dfy(19,12): Error: LHS of assignment does not denote a mutable field
IteratorResolution.dfy(123,9): Error: unresolved identifier: _decreases3
IteratorResolution.dfy(124,21): Error: arguments must have the same type (got int and ?)
IteratorResolution.dfy(125,14): Error: LHS of assignment does not denote a mutable field
IteratorResolution.dfy(132,9): Error: unresolved identifier: _decreases1
IteratorResolution.dfy(137,9): Error: unresolved identifier: _decreases0
12 resolution/type errors detected in IteratorResolution.dfy

-------------------- Iterators.dfy --------------------
Iterators.dfy(248,9): Error: failure to decrease termination measure
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Else
Iterators.dfy(271,9): Error: failure to decrease termination measure
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Else
Iterators.dfy(281,24): Error: failure to decrease termination measure
Execution trace:
    (0,0): anon0
Iterators.dfy(293,9): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Else
Iterators.dfy(314,9): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Else
Iterators.dfy(323,24): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
Iterators.dfy(340,9): Error: failure to decrease termination measure
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Else
Iterators.dfy(350,24): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
Iterators.dfy(367,9): Error: failure to decrease termination measure
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Else
Iterators.dfy(100,22): Error: assertion violation
Execution trace:
    (0,0): anon0
Iterators.dfy(103,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then
    (0,0): anon3
Iterators.dfy(174,28): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon15_Then
Iterators.dfy(205,7): Error: an assignment to _new is only allowed to shrink the set
Execution trace:
    (0,0): anon0
    Iterators.dfy(194,3): anon16_LoopHead
    (0,0): anon16_LoopBody
    Iterators.dfy(194,3): anon17_Else
    Iterators.dfy(194,3): anon19_Else
    (0,0): anon20_Then
Iterators.dfy(209,21): Error: assertion violation
Execution trace:
    (0,0): anon0
    Iterators.dfy(194,3): anon16_LoopHead
    (0,0): anon16_LoopBody
    Iterators.dfy(194,3): anon17_Else
    Iterators.dfy(194,3): anon19_Else
    (0,0): anon21_Then
Iterators.dfy(37,14): Error BP5002: A precondition for this call might not hold.
Iterators.dfy(1,10): Related location: This is the precondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon35_Then
    (0,0): anon2
    (0,0): anon36_Then
    (0,0): anon5
    (0,0): anon37_Then
Iterators.dfy(86,14): Error: assertion violation
Execution trace:
    (0,0): anon0
Iterators.dfy(116,16): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
Iterators.dfy(147,16): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
Iterators.dfy(152,16): Error BP5002: A precondition for this call might not hold.
Iterators.dfy(122,10): Related location: This is the precondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then
    (0,0): anon3
Iterators.dfy(231,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    Iterators.dfy(222,3): anon14_LoopHead
    (0,0): anon14_LoopBody
    Iterators.dfy(222,3): anon15_Else
    Iterators.dfy(222,3): anon18_Else
    (0,0): anon19_Else

Dafny program verifier finished with 65 verified, 20 errors

-------------------- RankPos.dfy --------------------

Dafny program verifier finished with 11 verified, 0 errors

-------------------- RankNeg.dfy --------------------
RankNeg.dfy(7,26): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Then
RankNeg.dfy(12,28): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Then
RankNeg.dfy(19,31): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Then
RankNeg.dfy(29,25): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Then

Dafny program verifier finished with 1 verified, 4 errors

-------------------- Computations.dfy --------------------

Dafny program verifier finished with 46 verified, 0 errors

-------------------- ComputationsNeg.dfy --------------------
ComputationsNeg.dfy(4,3): Error: failure to decrease termination measure
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
ComputationsNeg.dfy(8,1): Error BP5003: A postcondition might not hold on this return path.
ComputationsNeg.dfy(7,17): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
ComputationsNeg.dfy(20,1): Error BP5003: A postcondition might not hold on this return path.
ComputationsNeg.dfy(19,11): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 3 verified, 3 errors

-------------------- Include.dfy --------------------

Dafny program verifier finished with 2 verified, 0 errors

-------------------- Superposition.dfy --------------------

Verifying CheckWellformed$$_0_M0.C.M ...
  [0 proof obligations]  verified

Verifying Impl$$_0_M0.C.M ...
  [4 proof obligations]  verified

Verifying CheckWellformed$$_0_M0.C.P ...
  [4 proof obligations]  verified

Verifying CheckWellformed$$_0_M0.C.Q ...
  [3 proof obligations]  error
Superposition.dfy(24,15): Error BP5003: A postcondition might not hold on this return path.
Superposition.dfy(25,26): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else

Verifying CheckWellformed$$_0_M0.C.R ...
  [3 proof obligations]  error
Superposition.dfy(30,15): Error BP5003: A postcondition might not hold on this return path.
Superposition.dfy(31,26): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else

Verifying CheckWellformed$$_1_M1.C.M ...
  [0 proof obligations]  verified

Verifying Impl$$_1_M1.C.M ...
  [1 proof obligation]  verified

Verifying CheckWellformed$$_1_M1.C.P ...
  [1 proof obligation]  error
Superposition.dfy(47,15): Error BP5003: A postcondition might not hold on this return path.
Superposition.dfy[M1](19,26): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon7_Else
    (0,0): anon9_Then
    (0,0): anon6

Verifying CheckWellformed$$_1_M1.C.Q ...
  [0 proof obligations]  verified

Verifying CheckWellformed$$_1_M1.C.R ...
  [0 proof obligations]  verified

Dafny program verifier finished with 7 verified, 3 errors

-------------------- SmallTests.dfy --------------------
SmallTests.dfy(30,11): Error: index out of range
Execution trace:
    (0,0): anon0
SmallTests.dfy(61,36): Error: possible division by zero
Execution trace:
    (0,0): anon0
    (0,0): anon12_Then
SmallTests.dfy(62,51): Error: possible division by zero
Execution trace:
    (0,0): anon0
    (0,0): anon12_Else
    (0,0): anon3
    (0,0): anon13_Else
SmallTests.dfy(63,22): Error: target object may be null
Execution trace:
    (0,0): anon0
    (0,0): anon12_Then
    (0,0): anon3
    (0,0): anon13_Then
    (0,0): anon6
SmallTests.dfy(82,24): Error: target object may be null
Execution trace:
    (0,0): anon0
    SmallTests.dfy(81,5): anon8_LoopHead
    (0,0): anon8_LoopBody
    (0,0): anon9_Then
SmallTests.dfy(116,5): Error: call may violate context's modifies clause
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
    (0,0): anon3
SmallTests.dfy(129,9): Error: call may violate context's modifies clause
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
SmallTests.dfy(131,9): Error: call may violate context's modifies clause
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
SmallTests.dfy(171,9): Error: assignment may update an object field not in the enclosing context's modifies clause
Execution trace:
    (0,0): anon0
    (0,0): anon22_Else
    (0,0): anon24_Else
    (0,0): anon26_Else
    (0,0): anon28_Then
    (0,0): anon29_Then
    (0,0): anon19
SmallTests.dfy(195,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon6_Then
SmallTests.dfy(202,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
    (0,0): anon3
    (0,0): anon7_Then
SmallTests.dfy(204,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
    (0,0): anon3
    (0,0): anon7_Else
SmallTests.dfy(250,24): Error BP5002: A precondition for this call might not hold.
SmallTests.dfy(228,30): Related location: This is the precondition that might not hold.
Execution trace:
    (0,0): anon0
    SmallTests.dfy(245,19): anon3_Else
    (0,0): anon2
SmallTests.dfy(355,12): Error: assertion violation
Execution trace:
    (0,0): anon0
SmallTests.dfy(365,12): Error: assertion violation
Execution trace:
    (0,0): anon0
SmallTests.dfy(375,6): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
SmallTests.dfy(679,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    SmallTests.dfy(676,5): anon7_LoopHead
    (0,0): anon7_LoopBody
    SmallTests.dfy(676,5): anon8_Else
    (0,0): anon9_Then
SmallTests.dfy(700,14): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon7_Then
    (0,0): anon8_Then
    (0,0): anon3
SmallTests.dfy(285,3): Error BP5003: A postcondition might not hold on this return path.
SmallTests.dfy(279,11): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon18_Else
    (0,0): anon23_Then
    (0,0): anon24_Then
    (0,0): anon15
    (0,0): anon25_Else
SmallTests.dfy(326,12): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon8_Then
    (0,0): anon7
SmallTests.dfy(333,10): Error: assertion violation
Execution trace:
    (0,0): anon0
SmallTests.dfy(343,4): Error: cannot prove termination; try supplying a decreases clause
Execution trace:
    (0,0): anon0
    (0,0): anon3_Else
SmallTests.dfy(387,10): Error BP5003: A postcondition might not hold on this return path.
SmallTests.dfy(390,41): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    (0,0): anon6_Else
SmallTests.dfy(550,12): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
    (0,0): anon2
SmallTests.dfy(564,20): Error: left-hand sides 0 and 1 may refer to the same location
Execution trace:
    (0,0): anon0
    (0,0): anon27_Then
    (0,0): anon28_Then
    (0,0): anon4
    (0,0): anon29_Then
    (0,0): anon30_Then
    (0,0): anon9
    (0,0): anon31_Then
    (0,0): anon32_Then
    (0,0): anon12
SmallTests.dfy(566,15): Error: left-hand sides 1 and 2 may refer to the same location
Execution trace:
    (0,0): anon0
    (0,0): anon27_Then
    SmallTests.dfy(559,18): anon28_Else
    (0,0): anon4
    (0,0): anon29_Else
    (0,0): anon30_Then
    (0,0): anon9
    (0,0): anon31_Else
    (0,0): anon35_Then
    (0,0): anon36_Then
    (0,0): anon37_Then
    (0,0): anon22
    (0,0): anon38_Then
SmallTests.dfy(573,25): Error: target object may be null
Execution trace:
    (0,0): anon0
SmallTests.dfy(586,10): Error: assertion violation
Execution trace:
    (0,0): anon0
SmallTests.dfy(610,5): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SmallTests.dfy(633,10): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon8_Then
    (0,0): anon9_Then
    (0,0): anon4
    (0,0): anon10_Then
    (0,0): anon7
SmallTests.dfy(647,10): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
    (0,0): anon6_Then
    (0,0): anon3
SmallTests.dfy(649,10): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
SmallTests.dfy(662,9): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 87 verified, 33 errors

Dafny program verifier finished with 0 verified, 0 errors

-------------------- LetExpr.dfy --------------------
LetExpr.dfy(5,12): Error: assertion violation
Execution trace:
    (0,0): anon0
LetExpr.dfy(104,21): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon11_Then

Dafny program verifier finished with 28 verified, 2 errors

Dafny program verifier finished with 0 verified, 0 errors

-------------------- Calculations.dfy --------------------
Calculations.dfy(3,6): Error: index out of range
Execution trace:
    (0,0): anon0
    (0,0): anon24_Then
Calculations.dfy(8,15): Error: index out of range
Execution trace:
    (0,0): anon0
    (0,0): anon26_Then
Calculations.dfy(8,19): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon26_Then
Calculations.dfy(52,12): Error: assertion violation
Execution trace:
    (0,0): anon0
    Calculations.dfy(47,3): anon5_Else
Calculations.dfy(75,15): Error: index out of range
Execution trace:
    (0,0): anon0
    (0,0): anon12_Then
Calculations.dfy(75,19): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon12_Then

Dafny program verifier finished with 9 verified, 6 errors

Dafny program verifier finished with 0 verified, 0 errors

Dafny program verifier finished with 44 verified, 0 errors
Compiled assembly into Compilation.exe

Dafny program verifier finished with 15 verified, 0 errors
Compilation error: Arbitrary type ('_module.MyType') cannot be compiled
Compilation error: Iterator _module.Iter has no body
Compilation error: Method _module._default.M has no body
Compilation error: Method _module._default.P has no body
Compilation error: an assume statement cannot be compiled (line 8)
Compilation error: Function _module._default.F has no body
Compilation error: Function _module._default.H has no body
Compilation error: an assume statement cannot be compiled (line 17)
Compilation error: an assume statement cannot be compiled (line 20)
Compilation error: an assume statement cannot be compiled (line 25)
Compilation error: an assume statement cannot be compiled (line 34)
